<Workspace Version="1.2.1.3083" X="-127.007227107781" Y="228.756611773401" zoom="1.62766375666706" Name="Springs.Collector.ElementsInView" Description="Selects all elements visible in the input view." ID="b5bdff96-365e-44a7-af60-1cf3936c4b36" Category="Springs.Revit.Collectors">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="73ecd3f5-0bbc-420b-93a8-bf519b6c8b50" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250.614377506353" y="36.8658437845678" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>#Copyright(c) 2016, Dimitar Venkov
# @5devene, dimitar.ven@gmail.com

import clr

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import FilteredElementCollector

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

def tolist(obj1):
	if hasattr(obj1,"__iter__"): return obj1
	else: return [obj1]
def output1(l1):
	if len(l1) == 1: return l1[0]
	else: return l1

views = UnwrapElement(tolist(IN[0]) )
cat = UnwrapElement(IN[1])
elements = []

for i in xrange(len(views)):
	if cat is not None:
		fec = FilteredElementCollector(doc, views[i].Id).WhereElementIsNotElementType().OfCategoryId(cat.Id).GetElementIterator()
	else:
		fec = FilteredElementCollector(doc, views[i].Id).WhereElementIsNotElementType().GetElementIterator()
	fec.Reset()
	view_el = []
	while fec.MoveNext():
		view_el.append(fec.Current.ToDSType(True) )
	elements.append(view_el)
OUT = output1(elements)</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="9b4fce8f-07d7-4c34-aee2-a2ebd75460eb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="388.930361453654" y="39.0418971780411" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="element(s)" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="552eab9b-8333-42d4-9d3a-afe5928c2d4b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="97.565975877496" y="-1.5223178974025" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="view:var[]" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="79e7a498-ca8d-4741-bab2-f803ed22952d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="27.6628605202166" y="63.8069449123469" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="category:var = null" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="2740782b-610f-4dda-9701-5a30b80e2ad0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="28.4021912457163" y="127.856497777674" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="refresh:bool = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="73ecd3f5-0bbc-420b-93a8-bf519b6c8b50" start_index="0" end="9b4fce8f-07d7-4c34-aee2-a2ebd75460eb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="552eab9b-8333-42d4-9d3a-afe5928c2d4b" start_index="0" end="73ecd3f5-0bbc-420b-93a8-bf519b6c8b50" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="79e7a498-ca8d-4741-bab2-f803ed22952d" start_index="0" end="73ecd3f5-0bbc-420b-93a8-bf519b6c8b50" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2740782b-610f-4dda-9701-5a30b80e2ad0" start_index="0" end="73ecd3f5-0bbc-420b-93a8-bf519b6c8b50" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>