<Workspace Version="1.2.1.3083" X="109.44546210666" Y="75.4504162067256" zoom="0.983096703456758" ScaleFactor="1" Name="Springs.Star.ByCenterRadiusRays" Description="Fun little node to create star shapes." ID="274bb472-d985-49b8-ad53-307495a00169" Category="Springs.Geometry">
  <NamespaceResolutionMap>
    <ClassMap partialName="PolyCurve" resolvedName="Autodesk.DesignScript.Geometry.PolyCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Circle" resolvedName="Autodesk.DesignScript.Geometry.Circle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f24dfb85-bd65-4d5b-84e3-355e47bf3bed" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-108.484156622764" y="371.001152292042" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="NumberOfRays:int = 7" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="10c56a96-d4d8-4aee-96eb-19bf98297663" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-200.649928927769" y="134.034232005739" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="StarOrigin:Point = Point.Origin()" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="56f3bfe0-5c43-4475-bd23-7e908c56557d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-113.819788643682" y="200.682241508417" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="StarRadius:double = 5" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="8f7bc9d1-5f61-48b9-bd2b-5fbad4845dc5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-128.047262224142" y="272.905385935235" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RayPercentage:double = 55" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3bb30201-8bee-48be-9609-d586bfe88871" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="473.969913545865" y="231.9979360249" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="PolyCurve" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="2ac2a89a-6afb-4ffd-b397-d8e19c845405" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="203.7462621473" y="227.081320130767" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="star1(p1,r1,s,n);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="09fce267-a7ec-4539-baee-75602255722f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="149.321368702917" y="-44.968108112358" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="def star1(p1,r1,s,n)&#xA;{&#xA;c1 = Circle.ByCenterPointRadius(p1,r1);&#xA;c2 = Circle.ByCenterPointRadius(p1,r1*(99.9-s)/100);&#xA;pts1 = c1.PointAtParameter(0..1..#n+1);&#xA;//testR = n % 2 == 0;&#xA;pts2a = c2.PointAtParameter(0..1..#n*2+1);&#xA;pts2b = DSCore.List.TakeEveryNthItem(pts2a,2,0);&#xA;pts3 = Flatten(List.Transpose({pts1,pts2b}));&#xA;pts3c = DSCore.List.DropItems(pts3,-1);&#xA;return = PolyCurve.ByPoints(pts3c);&#xA;};" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f24dfb85-bd65-4d5b-84e3-355e47bf3bed" start_index="0" end="2ac2a89a-6afb-4ffd-b397-d8e19c845405" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="10c56a96-d4d8-4aee-96eb-19bf98297663" start_index="0" end="2ac2a89a-6afb-4ffd-b397-d8e19c845405" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="56f3bfe0-5c43-4475-bd23-7e908c56557d" start_index="0" end="2ac2a89a-6afb-4ffd-b397-d8e19c845405" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8f7bc9d1-5f61-48b9-bd2b-5fbad4845dc5" start_index="0" end="2ac2a89a-6afb-4ffd-b397-d8e19c845405" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2ac2a89a-6afb-4ffd-b397-d8e19c845405" start_index="0" end="3bb30201-8bee-48be-9609-d586bfe88871" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="13.4373044967651" eyeY="99.6964797973633" eyeZ="39.3309211730957" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>